/**
 * Approximate trailhead coordinates keyed by preset slug. Layered
 * over TRAIL_LIBRARY so we can add matcher coverage without editing
 * every entry inline — accessed via presetWithCoords() below.
 *
 * Coords are trailhead / start-point WGS84 lat/lng. Precision ~50m
 * is plenty for the historical matcher (5 km radius). Source:
 * NPS.gov trailhead lookups + widely-cited guidebook coords.
 */

import { TRAIL_LIBRARY, type TrailPreset } from "./trail-library";
import { withDetails } from "./trail-details";

export const TRAIL_COORDS: Record<string, { lat: number; lng: number }> = {
  // Rocky Mountain NP
  "longs-keyhole": { lat: 40.2717, lng: -105.5567 },
  "sky-pond": { lat: 40.3105, lng: -105.6403 },
  "chasm-lake": { lat: 40.2717, lng: -105.5567 },

  // Zion NP
  "angels-landing": { lat: 37.2589, lng: -112.9500 },
  "observation-point-zion": { lat: 37.2664, lng: -112.9358 },
  "zion-narrows-bottomup": { lat: 37.2841, lng: -112.9469 },

  // Grand Canyon NP
  "gc-bright-angel-plateau": { lat: 36.0576, lng: -112.1436 },
  "gc-south-kaibab-ooh-aah": { lat: 36.0533, lng: -112.0847 },
  "gc-rim-to-rim": { lat: 36.0533, lng: -112.0847 },

  // Glacier NP
  "highline-glacier": { lat: 48.6961, lng: -113.7175 },
  "grinnell-glacier": { lat: 48.7975, lng: -113.6708 },
  "iceberg-lake": { lat: 48.7972, lng: -113.6714 },

  // Acadia NP
  "precipice-trail": { lat: 44.3506, lng: -68.1867 },
  "beehive-loop": { lat: 44.3311, lng: -68.1806 },

  // Great Smoky Mountains NP
  "alum-cave-leconte": { lat: 35.6289, lng: -83.4514 },

  // Rainier NP (existing, in case Mayank's Skyline hike triggers)
  "skyline-paradise": { lat: 46.7856, lng: -121.7367 },
  "rainier-dc": { lat: 46.7856, lng: -121.7367 },
  "rainier-emmons": { lat: 46.8547, lng: -121.6408 },
  "camp-muir-dayhike": { lat: 46.7856, lng: -121.7367 },
};

/**
 * Extra presets for parks in the user's history that aren't in the
 * main TRAIL_LIBRARY yet. Same shape as TrailPreset. Concatenated
 * into the effective library by getFullTrailLibrary() below.
 */
export const EXTRA_TRAIL_PRESETS: TrailPreset[] = [
  // ────── Yellowstone NP ──────
  {
    slug: "yellowstone-fairy-falls",
    name: "Fairy Falls + Grand Prismatic Overlook",
    region: "Yellowstone NP · WY",
    country: "US",
    distanceKm: 8.4,
    elevationGainFt: 200,
    maxAltitudeFt: 7500,
    typicalHours: 2.5,
    packWeightLb: 5,
    terrainGrade: "easy",
    notes:
      "Flat, wide trail to the overlook + waterfall. Very popular; go early. Optional side-trip to Imperial Geyser adds ~2 miles.",
    sources: ["NPS.gov", "AllTrails consensus"],
    startLat: 44.5216,
    startLng: -110.8322,
  },
  {
    slug: "yellowstone-mount-washburn",
    name: "Mount Washburn (Dunraven Pass)",
    region: "Yellowstone NP · WY",
    country: "US",
    distanceKm: 10.4,
    elevationGainFt: 1400,
    maxAltitudeFt: 10243,
    typicalHours: 4,
    packWeightLb: 8,
    terrainGrade: "moderate",
    notes:
      "Old service road ascent to a fire lookout with panoramic caldera views. Watch for bighorn sheep. Exposed above treeline — check afternoon weather.",
    sources: ["NPS.gov"],
    startLat: 44.7900,
    startLng: -110.4372,
  },
  {
    slug: "yellowstone-elephant-back",
    name: "Elephant Back Loop",
    region: "Yellowstone NP · WY",
    country: "US",
    distanceKm: 5.6,
    elevationGainFt: 800,
    maxAltitudeFt: 8600,
    typicalHours: 2.5,
    packWeightLb: 5,
    terrainGrade: "moderate",
    notes:
      "Quick uphill grunt to a panoramic overlook of Yellowstone Lake. Bear country — carry spray.",
    sources: ["NPS.gov"],
    startLat: 44.5636,
    startLng: -110.4083,
  },

  // ────── Sedona · Coconino NF ──────
  {
    slug: "sedona-devils-bridge",
    name: "Devil's Bridge",
    region: "Sedona · Coconino NF · AZ",
    country: "US",
    distanceKm: 6.4,
    elevationGainFt: 500,
    maxAltitudeFt: 4900,
    typicalHours: 2,
    packWeightLb: 5,
    terrainGrade: "moderate",
    notes:
      "Iconic natural sandstone arch. Final scramble is exposed but short. Crowded — go at sunrise. Access via Dry Creek Rd (high-clearance from Chuckwagon TH).",
    sources: ["USFS", "AllTrails consensus"],
    startLat: 34.9019,
    startLng: -111.8125,
  },
  {
    slug: "sedona-cathedral-rock",
    name: "Cathedral Rock",
    region: "Sedona · Coconino NF · AZ",
    country: "US",
    distanceKm: 2.1,
    elevationGainFt: 750,
    maxAltitudeFt: 4967,
    typicalHours: 1.5,
    packWeightLb: 3,
    terrainGrade: "moderate",
    notes:
      "Short but steep sandstone scramble to a saddle between spires. Class 2-3 moves on slickrock — dry conditions only.",
    sources: ["USFS"],
    startLat: 34.8231,
    startLng: -111.7778,
  },
  {
    slug: "sedona-west-fork",
    name: "West Fork of Oak Creek",
    region: "Sedona · Coconino NF · AZ",
    country: "US",
    distanceKm: 11.3,
    elevationGainFt: 300,
    maxAltitudeFt: 5400,
    typicalHours: 4,
    packWeightLb: 5,
    terrainGrade: "easy",
    notes:
      "Flat canyon walk with 13 stream crossings — waterproof footwear or wading shoes. Fall foliage October-early November. Fee area.",
    sources: ["USFS"],
    startLat: 34.9906,
    startLng: -111.7444,
  },
  {
    slug: "sedona-bell-rock",
    name: "Bell Rock Pathway",
    region: "Sedona · Coconino NF · AZ",
    country: "US",
    distanceKm: 6.1,
    elevationGainFt: 200,
    maxAltitudeFt: 4700,
    typicalHours: 2,
    packWeightLb: 3,
    terrainGrade: "easy",
    notes:
      "Wide, mostly-flat path around Bell Rock. Optional scrambles onto the rock itself add difficulty and vertical.",
    sources: ["USFS"],
    startLat: 34.8069,
    startLng: -111.7669,
  },

  // ────── Bryce Canyon NP ──────
  {
    slug: "bryce-navajo-queens",
    name: "Navajo Loop + Queen's Garden (Figure 8)",
    region: "Bryce NP · UT",
    country: "US",
    distanceKm: 4.8,
    elevationGainFt: 600,
    maxAltitudeFt: 8000,
    typicalHours: 2.5,
    packWeightLb: 5,
    terrainGrade: "moderate",
    notes:
      "The classic Bryce sampler. Down Wall Street (Navajo), across the amphitheater, up Queen's Garden back to Sunrise Point. Descend first, climb out at end.",
    sources: ["NPS.gov"],
    startLat: 37.6247,
    startLng: -112.1636,
  },
  {
    slug: "bryce-peekaboo-loop",
    name: "Peekaboo Loop",
    region: "Bryce NP · UT",
    country: "US",
    distanceKm: 8.2,
    elevationGainFt: 1500,
    maxAltitudeFt: 8300,
    typicalHours: 3.5,
    packWeightLb: 6,
    terrainGrade: "moderate",
    notes:
      "Deeper into the hoodoos than Navajo. Shared with horses on some sections. Elevation makes the return climb feel like more work than the mileage suggests.",
    sources: ["NPS.gov"],
    startLat: 37.6053,
    startLng: -112.1500,
  },
  {
    slug: "bryce-fairyland-loop",
    name: "Fairyland Loop",
    region: "Bryce NP · UT",
    country: "US",
    distanceKm: 12.9,
    elevationGainFt: 1700,
    maxAltitudeFt: 8100,
    typicalHours: 5,
    packWeightLb: 8,
    terrainGrade: "hard",
    notes:
      "The best long day at Bryce — less crowded than the amphitheater loops. Big elevation change; carry water, no shade.",
    sources: ["NPS.gov"],
    startLat: 37.6444,
    startLng: -112.1478,
  },

  // ────── Petrified Forest NP ──────
  {
    slug: "petrified-blue-mesa",
    name: "Blue Mesa Trail",
    region: "Petrified Forest NP · AZ",
    country: "US",
    distanceKm: 1.6,
    elevationGainFt: 100,
    maxAltitudeFt: 5700,
    typicalHours: 1,
    packWeightLb: 3,
    terrainGrade: "easy",
    notes:
      "Short paved loop through blue-and-purple badlands with petrified wood scattered along the trail. Very photogenic.",
    sources: ["NPS.gov"],
    startLat: 34.9450,
    startLng: -109.7822,
  },
  {
    slug: "petrified-crystal-forest",
    name: "Crystal Forest Trail",
    region: "Petrified Forest NP · AZ",
    country: "US",
    distanceKm: 1.2,
    elevationGainFt: 30,
    maxAltitudeFt: 5500,
    typicalHours: 0.75,
    packWeightLb: 3,
    terrainGrade: "easy",
    notes:
      "Flat loop showcasing the densest concentration of crystalline petrified logs. Wheelchair-accessible for the first section.",
    sources: ["NPS.gov"],
    startLat: 34.8125,
    startLng: -109.8756,
  },

  // ────── Rainier NP content pass (2026-08-25) ──────
  // First LLM-assisted bulk pass, verified against NPS.gov trail
  // pages for the safety-critical fields (max altitude, permit,
  // terrain grade). Other fields (distance, elevation, typical
  // hours) sourced from NPS + guidebook consensus and may need
  // ±5% tolerance. Skyline / DC / Emmons / Wonderland already
  // live in the base TRAIL_LIBRARY — this fills in the day-hike
  // and training-hike gaps around them.
  {
    slug: "naches-peak-loop",
    name: "Naches Peak Loop",
    region: "Rainier NP · Cascades",
    country: "US",
    distanceKm: 8.7,
    elevationGainFt: 700,
    maxAltitudeFt: 5900,
    typicalHours: 3,
    packWeightLb: 6,
    terrainGrade: "easy",
    notes:
      "Wildflower loop straddling the PCT with views of Rainier over Dewey Lake. Peaks late July through mid-August. Ridgeline exposure to weather in late afternoon.",
    sources: ["NPS.gov", "Washington Trails Association"],
    startLat: 46.8709,
    startLng: -121.5169,
  },
  {
    slug: "tolmie-peak-lookout",
    name: "Tolmie Peak Lookout",
    region: "Rainier NP · Cascades",
    country: "US",
    distanceKm: 10.5,
    elevationGainFt: 1600,
    maxAltitudeFt: 5940,
    typicalHours: 4,
    packWeightLb: 7,
    terrainGrade: "moderate",
    notes:
      "Mowich Lake side. Passes Eunice Lake before the final climb to the fire-lookout tower. North-face Rainier view.",
    sources: ["NPS.gov", "WTA"],
    startLat: 46.9339,
    startLng: -121.8621,
  },
  {
    slug: "comet-falls",
    name: "Comet Falls / Van Trump Park",
    region: "Rainier NP · Cascades",
    country: "US",
    distanceKm: 9.2,
    elevationGainFt: 1700,
    maxAltitudeFt: 5800,
    typicalHours: 4,
    packWeightLb: 7,
    terrainGrade: "moderate",
    notes:
      "One of the tallest waterfalls in the park (~300 ft). Van Trump Park continues into meadows above the falls; adds ~800 ft to reach it.",
    sources: ["NPS.gov", "WTA"],
    startLat: 46.7756,
    startLng: -121.7811,
  },
  {
    slug: "burroughs-mountain-2nd",
    name: "Burroughs Mountain (2nd Burroughs)",
    region: "Rainier NP · Cascades",
    country: "US",
    distanceKm: 11.3,
    elevationGainFt: 2500,
    maxAltitudeFt: 7402,
    typicalHours: 5,
    packWeightLb: 8,
    terrainGrade: "moderate",
    notes:
      "Arctic tundra above treeline on volcanic scree. Snowfields linger into August on the north slope. Continue to 3rd Burroughs (~1.5 mi more) for the closest walk-up view of Emmons Glacier.",
    sources: ["NPS.gov", "WTA"],
    startLat: 46.9147,
    startLng: -121.6425,
  },
  {
    slug: "fremont-lookout",
    name: "Mount Fremont Lookout",
    region: "Rainier NP · Cascades",
    country: "US",
    distanceKm: 9.2,
    elevationGainFt: 900,
    maxAltitudeFt: 7181,
    typicalHours: 3.5,
    packWeightLb: 7,
    terrainGrade: "moderate",
    notes:
      "Sunrise-side ridge walk to another fire-lookout tower. Marmots common. Ridge is exposed — turn back for lightning.",
    sources: ["NPS.gov", "WTA"],
    startLat: 46.9147,
    startLng: -121.6425,
  },
  {
    slug: "rampart-ridge-loop",
    name: "Rampart Ridge Loop",
    region: "Rainier NP · Cascades",
    country: "US",
    distanceKm: 7.4,
    elevationGainFt: 1300,
    maxAltitudeFt: 4058,
    typicalHours: 3,
    packWeightLb: 6,
    terrainGrade: "moderate",
    notes:
      "Old-growth Douglas fir loop from Longmire. Snow-free earlier and later than the alpine trails — good shoulder-season option.",
    sources: ["NPS.gov", "WTA"],
    startLat: 46.7503,
    startLng: -121.8144,
  },
  // Camp Muir day hike already lives in TRAIL_LIBRARY; details
  // overlay is applied via trail-details.ts. Adding a coord entry
  // for its trailhead so the matcher can score it.
  {
    slug: "pinnacle-peak-saddle",
    name: "Pinnacle Peak Saddle",
    region: "Rainier NP · Cascades",
    country: "US",
    distanceKm: 4.2,
    elevationGainFt: 1050,
    maxAltitudeFt: 6000,
    typicalHours: 2,
    packWeightLb: 5,
    terrainGrade: "moderate",
    notes:
      "Short but relentless climb from Reflection Lake to the saddle between Pinnacle and Plummer Peak. Summit push above the saddle is Class 2-3 scramble — most hikers stop at the saddle.",
    sources: ["NPS.gov", "WTA"],
    startLat: 46.7692,
    startLng: -121.7367,
  },
  {
    slug: "summerland",
    name: "Summerland",
    region: "Rainier NP · Cascades",
    country: "US",
    distanceKm: 13.5,
    elevationGainFt: 2100,
    maxAltitudeFt: 5900,
    typicalHours: 5.5,
    packWeightLb: 7,
    terrainGrade: "moderate",
    notes:
      "Wonderland Trail spur climbing to a bench of subalpine meadows and a stone shelter. Panhandle Gap adds another 1,300 ft and puts you above snow year-round.",
    sources: ["NPS.gov", "WTA"],
    startLat: 46.9083,
    startLng: -121.6519,
  },
  {
    slug: "silver-falls-loop",
    name: "Silver Falls Loop",
    region: "Rainier NP · Cascades",
    country: "US",
    distanceKm: 4.8,
    elevationGainFt: 300,
    maxAltitudeFt: 2200,
    typicalHours: 1.5,
    packWeightLb: 4,
    terrainGrade: "easy",
    notes:
      "Ohanapecosh-side old-growth loop past a wide cascading waterfall. Family-friendly, open most of the year.",
    sources: ["NPS.gov", "WTA"],
    startLat: 46.7381,
    startLng: -121.5644,
  },

  // ────── Hudson Highlands / Catskills / Shawangunks (NY) ──────
  // Added for the "near me" feed — the library was heavy on
  // expedition targets and thin on East Coast day-trip options,
  // which meant users in NYC / New England saw nothing under
  // /trails/discover's Near Me section. Trailhead coords sourced
  // from NY State Parks trailhead lookups + guidebook consensus.
  {
    slug: "bear-mountain-loop",
    name: "Bear Mountain Loop (Perkins Tower)",
    region: "Bear Mtn SP · NY",
    country: "US",
    distanceKm: 6.4,
    elevationGainFt: 1100,
    maxAltitudeFt: 1284,
    typicalHours: 3,
    packWeightLb: 6,
    terrainGrade: "moderate",
    notes:
      "Classic loop up the Major Welch, down the AT. Views of the Hudson from Perkins Tower. Popular — go early on weekends.",
    sources: ["NY State Parks", "AllTrails"],
    startLat: 41.3126,
    startLng: -73.9887,
  },
  {
    slug: "breakneck-ridge",
    name: "Breakneck Ridge",
    region: "Hudson Highlands · NY",
    country: "US",
    distanceKm: 5.6,
    elevationGainFt: 1250,
    maxAltitudeFt: 1260,
    typicalHours: 3,
    packWeightLb: 6,
    terrainGrade: "hard",
    notes:
      "Legendary scramble above the Hudson. Real Class 3 sections early — hand-over-hand near the ridge. Not for wet weather.",
    sources: ["NY State Parks", "Metro-North trailhead"],
    startLat: 41.4459,
    startLng: -73.9764,
  },
  {
    slug: "kaaterskill-high-peak",
    name: "Kaaterskill High Peak",
    region: "Catskills · NY",
    country: "US",
    distanceKm: 12.9,
    elevationGainFt: 1900,
    maxAltitudeFt: 3655,
    typicalHours: 6,
    packWeightLb: 8,
    terrainGrade: "hard",
    notes:
      "Long loop with a real summit and a plane-wreck detour. Trail is unmaintained in stretches — bring a map.",
    sources: ["NY DEC", "Catskill 3500 Club"],
    startLat: 42.1936,
    startLng: -74.0567,
  },
  {
    slug: "slide-mountain",
    name: "Slide Mountain (highest Catskill peak)",
    region: "Catskills · NY",
    country: "US",
    distanceKm: 11.3,
    elevationGainFt: 1800,
    maxAltitudeFt: 4180,
    typicalHours: 5.5,
    packWeightLb: 7,
    terrainGrade: "moderate",
    notes:
      "Highest peak in the Catskills, but a steady climb rather than a scramble. Good all-day workout close to NYC.",
    sources: ["NY DEC", "Catskill 3500 Club"],
    startLat: 41.9944,
    startLng: -74.4283,
  },
  {
    slug: "mount-tammany",
    name: "Mount Tammany (Kittatinny Ridge)",
    region: "Delaware Water Gap · NJ",
    country: "US",
    distanceKm: 5.5,
    elevationGainFt: 1250,
    maxAltitudeFt: 1526,
    typicalHours: 3,
    packWeightLb: 6,
    terrainGrade: "moderate",
    notes:
      "Steep first mile up the red-dot trail; ridge views over the Water Gap. Common overhanging rocks near the top.",
    sources: ["NPS.gov", "NY-NJ Trail Conf"],
    startLat: 40.9714,
    startLng: -75.1250,
  },
  {
    slug: "gertrudes-nose",
    name: "Gertrude's Nose Loop (Minnewaska)",
    region: "Shawangunks · NY",
    country: "US",
    distanceKm: 12.2,
    elevationGainFt: 1100,
    maxAltitudeFt: 2280,
    typicalHours: 4.5,
    packWeightLb: 6,
    terrainGrade: "moderate",
    notes:
      "Exposed cliff-edge loop with Catskills views. Sections along the rim have serious drops — no barriers.",
    sources: ["NY State Parks"],
    startLat: 41.7325,
    startLng: -74.2400,
  },
  {
    slug: "mount-marcy",
    name: "Mount Marcy (NY's high point)",
    region: "Adirondacks · NY",
    country: "US",
    distanceKm: 24.1,
    elevationGainFt: 3300,
    maxAltitudeFt: 5344,
    typicalHours: 10,
    packWeightLb: 12,
    terrainGrade: "hard",
    notes:
      "Long approach from Adirondak Loj via Van Hoevenberg. Exposed summit — weather changes fast above treeline.",
    sources: ["DEC", "ADK Guidebook"],
    startLat: 44.1830,
    startLng: -73.9647,
  },
  {
    slug: "cascade-mountain-adk",
    name: "Cascade Mountain (High Peaks starter)",
    region: "Adirondacks · NY",
    country: "US",
    distanceKm: 7.4,
    elevationGainFt: 1940,
    maxAltitudeFt: 4098,
    typicalHours: 4,
    packWeightLb: 6,
    terrainGrade: "moderate",
    notes:
      "Most accessible ADK 46er. Short, steep, bald summit with 360° views. Popular — parking fills by 7am on weekends.",
    sources: ["DEC", "ADK 46er Club"],
    startLat: 44.2211,
    startLng: -73.8617,
  },

  // ────── NYC-area content pass (2026-08-27) ──────
  // Popular day / weekend trails within ~5-hour drive of Manhattan.
  // Distances, gain, and max altitude sourced from NY-NJ Trail
  // Conference, DEC, state park pages, and guidebook consensus;
  // ±10% tolerance. Terrain grades err conservative for safety —
  // "hard" reserved for sustained Class 3 or exposed sections.

  // ────── Hudson Highlands (Rockland / Putnam / Orange counties, NY) ──────
  {
    slug: "anthonys-nose",
    name: "Anthony's Nose",
    region: "Hudson Highlands · NY",
    country: "US",
    distanceKm: 4.0,
    elevationGainFt: 720,
    maxAltitudeFt: 900,
    typicalHours: 2,
    packWeightLb: 4,
    terrainGrade: "moderate",
    notes:
      "Short, steep hike from the Bear Mountain Bridge to a Hudson-river overlook. Gets very busy on weekends.",
    sources: ["NY-NJ Trail Conf", "AllTrails"],
    startLat: 41.3210,
    startLng: -73.9737,
  },
  {
    slug: "popolopen-torne",
    name: "Popolopen Torne + Gorge Loop",
    region: "Bear Mtn / Harriman · NY",
    country: "US",
    distanceKm: 7.7,
    elevationGainFt: 1200,
    maxAltitudeFt: 942,
    typicalHours: 3.5,
    packWeightLb: 6,
    terrainGrade: "moderate",
    notes:
      "Rocky scramble to a memorial cairn summit with 360° views. The gorge return traverses a wooded ravine — good all-day loop under 4 hours.",
    sources: ["NY-NJ Trail Conf"],
    startLat: 41.3155,
    startLng: -74.0075,
  },
  {
    slug: "mount-beacon",
    name: "Mount Beacon",
    region: "Hudson Highlands · NY",
    country: "US",
    distanceKm: 6.4,
    elevationGainFt: 1540,
    maxAltitudeFt: 1610,
    typicalHours: 3,
    packWeightLb: 5,
    terrainGrade: "moderate",
    notes:
      "Steep stair-climb start from the abandoned incline railway, gentler ridge past the fire tower. Metro-North accessible from Beacon station.",
    sources: ["NY-NJ Trail Conf"],
    startLat: 41.4931,
    startLng: -73.9575,
  },
  {
    slug: "storm-king",
    name: "Storm King Mountain",
    region: "Hudson Highlands · NY",
    country: "US",
    distanceKm: 4.3,
    elevationGainFt: 1000,
    maxAltitudeFt: 1340,
    typicalHours: 2.5,
    packWeightLb: 5,
    terrainGrade: "moderate",
    notes:
      "Views of the Hudson and West Point from a bald rock summit. Multiple loop options from the Rt 9W trailhead.",
    sources: ["NY-NJ Trail Conf"],
    startLat: 41.4308,
    startLng: -74.0006,
  },
  {
    slug: "the-timp-harriman",
    name: "The Timp Loop (Harriman)",
    region: "Harriman SP · NY",
    country: "US",
    distanceKm: 12.5,
    elevationGainFt: 2100,
    maxAltitudeFt: 1080,
    typicalHours: 5,
    packWeightLb: 7,
    terrainGrade: "moderate",
    notes:
      "Under-visited Harriman loop over The Timp and West Mountain with several viewpoints down the Hudson toward Bear Mtn.",
    sources: ["NY-NJ Trail Conf"],
    startLat: 41.2839,
    startLng: -74.0119,
  },
  {
    slug: "almost-perpendicular-harriman",
    name: "Almost Perpendicular + Lake Skannatati",
    region: "Harriman SP · NY",
    country: "US",
    distanceKm: 8.5,
    elevationGainFt: 900,
    maxAltitudeFt: 1200,
    typicalHours: 3.5,
    packWeightLb: 5,
    terrainGrade: "moderate",
    notes:
      "Named for a striking cliff view over Lake Skannatati. Easy-to-follow loop combining Long Path + Red Cross Trail.",
    sources: ["NY-NJ Trail Conf"],
    startLat: 41.2578,
    startLng: -74.1236,
  },

  // ────── Catskills ──────
  {
    slug: "overlook-mountain",
    name: "Overlook Mountain (Woodstock)",
    region: "Catskills · NY",
    country: "US",
    distanceKm: 8.0,
    elevationGainFt: 1400,
    maxAltitudeFt: 3140,
    typicalHours: 3.5,
    packWeightLb: 5,
    terrainGrade: "moderate",
    notes:
      "Wide gravel fire road to a lookout tower + abandoned hotel ruins above Woodstock. Steady grade, no technical sections.",
    sources: ["NY DEC", "Catskill 3500 Club"],
    startLat: 42.0620,
    startLng: -74.1092,
  },
  {
    slug: "devils-path",
    name: "Devil's Path (thru-hike)",
    region: "Catskills · NY",
    country: "US",
    distanceKm: 38.6,
    elevationGainFt: 9000,
    maxAltitudeFt: 3980,
    typicalHours: 14,
    packWeightLb: 25,
    terrainGrade: "hard",
    notes:
      "24-mile chain over 6 Catskill high peaks. Rated the toughest day-hike in the East — sustained scrambling, exposure, no bailouts on ridges. Typically 2 days with a car shuttle.",
    sources: ["NY DEC", "Catskill 3500 Club", "Backpacker Magazine"],
    startLat: 42.1636,
    startLng: -74.1364,
  },
  {
    slug: "wittenberg-cornell-slide",
    name: "Wittenberg–Cornell–Slide Traverse",
    region: "Catskills · NY",
    country: "US",
    distanceKm: 27.4,
    elevationGainFt: 4300,
    maxAltitudeFt: 4180,
    typicalHours: 10,
    packWeightLb: 12,
    terrainGrade: "hard",
    notes:
      "The three highest Catskill peaks in one push. Requires a car shuttle. Slide is the roof of the Catskills at 4,180 ft.",
    sources: ["NY DEC", "Catskill 3500 Club"],
    startLat: 41.9756,
    startLng: -74.3767,
  },
  {
    slug: "giant-ledge-panther",
    name: "Giant Ledge + Panther Mountain",
    region: "Catskills · NY",
    country: "US",
    distanceKm: 10.5,
    elevationGainFt: 1900,
    maxAltitudeFt: 3720,
    typicalHours: 5,
    packWeightLb: 7,
    terrainGrade: "moderate",
    notes:
      "Giant Ledge alone is 3 miles round-trip with great views; continuing to Panther Mountain doubles the outing. Popular training hike for Catskill 3500.",
    sources: ["NY DEC", "Catskill 3500 Club"],
    startLat: 42.0089,
    startLng: -74.4278,
  },
  {
    slug: "hunter-mountain-fire-tower",
    name: "Hunter Mountain (Fire Tower)",
    region: "Catskills · NY",
    country: "US",
    distanceKm: 12.9,
    elevationGainFt: 2100,
    maxAltitudeFt: 4040,
    typicalHours: 5.5,
    packWeightLb: 7,
    terrainGrade: "moderate",
    notes:
      "Second-highest Catskill peak. Fire tower at the summit is climbable when open. Devil's Path variant is much harder — this is the classic Spruceton approach.",
    sources: ["NY DEC", "Catskill 3500 Club"],
    startLat: 42.1806,
    startLng: -74.2464,
  },
  {
    slug: "table-peekamoose",
    name: "Table + Peekamoose Traverse",
    region: "Catskills · NY",
    country: "US",
    distanceKm: 16.1,
    elevationGainFt: 2900,
    maxAltitudeFt: 3847,
    typicalHours: 7,
    packWeightLb: 8,
    terrainGrade: "hard",
    notes:
      "Two of the Catskill 3500s in a linear traverse. Remote, minimal signage, blowdown likely — a proper Catskill wilderness day.",
    sources: ["NY DEC", "Catskill 3500 Club"],
    startLat: 41.9086,
    startLng: -74.3706,
  },
  {
    slug: "north-point-escarpment",
    name: "North Point (Escarpment Trail)",
    region: "Catskills · NY",
    country: "US",
    distanceKm: 8.5,
    elevationGainFt: 1300,
    maxAltitudeFt: 3000,
    typicalHours: 4,
    packWeightLb: 6,
    terrainGrade: "moderate",
    notes:
      "Cliff-edge walk on the Escarpment Trail past the site of the old Catskill Mountain House. Iconic Hudson Valley views.",
    sources: ["NY DEC"],
    startLat: 42.1936,
    startLng: -74.0625,
  },
  {
    slug: "kaaterskill-falls",
    name: "Kaaterskill Falls",
    region: "Catskills · NY",
    country: "US",
    distanceKm: 4.0,
    elevationGainFt: 700,
    maxAltitudeFt: 2200,
    typicalHours: 2,
    packWeightLb: 4,
    terrainGrade: "easy",
    notes:
      "Two-tiered 260-ft waterfall — one of the tallest in NY. Viewing platform at the top; also accessible from below on Rt 23A.",
    sources: ["NY DEC"],
    startLat: 42.1917,
    startLng: -74.0625,
  },

  // ────── Shawangunks ──────
  {
    slug: "sams-point-ice-caves",
    name: "Sam's Point + Ice Caves Loop",
    region: "Shawangunks · NY",
    country: "US",
    distanceKm: 12.9,
    elevationGainFt: 1400,
    maxAltitudeFt: 2255,
    typicalHours: 4.5,
    packWeightLb: 6,
    terrainGrade: "moderate",
    notes:
      "White-quartz Shawangunk conglomerate cliffs, walk-through ice caves, Verkeerder Falls detour. Best in cool weather — the caves hold ice into June.",
    sources: ["NY State Parks"],
    startLat: 41.6633,
    startLng: -74.3628,
  },
  {
    slug: "bonticou-crag",
    name: "Bonticou Crag Scramble",
    region: "Shawangunks · NY",
    country: "US",
    distanceKm: 6.0,
    elevationGainFt: 800,
    maxAltitudeFt: 1194,
    typicalHours: 3,
    packWeightLb: 5,
    terrainGrade: "hard",
    notes:
      "Class 3 hand-over-hand scramble up a boulder ridge — one of the most exposed non-technical routes in the Hudson Valley. Down via the easier Northeast Trail.",
    sources: ["Mohonk Preserve"],
    startLat: 41.7761,
    startLng: -74.1653,
  },
  {
    slug: "millbrook-mountain",
    name: "Millbrook Mountain via Coxing Kill",
    region: "Shawangunks · NY",
    country: "US",
    distanceKm: 12.9,
    elevationGainFt: 1400,
    maxAltitudeFt: 1690,
    typicalHours: 5,
    packWeightLb: 6,
    terrainGrade: "moderate",
    notes:
      "Cliff-top plateau of the Trapps with Wallkill Valley views. Trails cross the Mohonk Preserve — day pass required.",
    sources: ["Mohonk Preserve"],
    startLat: 41.7392,
    startLng: -74.1786,
  },

  // ────── New Jersey / Delaware Water Gap ──────
  {
    slug: "sunfish-pond-dwg",
    name: "Sunfish Pond via AT",
    region: "Delaware Water Gap · NJ",
    country: "US",
    distanceKm: 12.9,
    elevationGainFt: 1300,
    maxAltitudeFt: 1500,
    typicalHours: 5,
    packWeightLb: 6,
    terrainGrade: "moderate",
    notes:
      "Glacial pond on the Kittatinny Ridge, reached via the Appalachian Trail from Dunnfield Creek. Rocky AT terrain — solid ankle support helps.",
    sources: ["NPS.gov"],
    startLat: 40.9700,
    startLng: -75.1275,
  },
  {
    slug: "mount-minsi",
    name: "Mount Minsi (PA-side Water Gap)",
    region: "Delaware Water Gap · PA",
    country: "US",
    distanceKm: 8.5,
    elevationGainFt: 1200,
    maxAltitudeFt: 1461,
    typicalHours: 3.5,
    packWeightLb: 5,
    terrainGrade: "moderate",
    notes:
      "PA counterpart to Mt Tammany. Loops via AT and the Table Rock old road. Less crowded than Tammany.",
    sources: ["NPS.gov"],
    startLat: 40.9736,
    startLng: -75.1439,
  },
  {
    slug: "wyanokie-high-point",
    name: "Wyanokie High Point + Chikahoki Falls",
    region: "Norvin Green SF · NJ",
    country: "US",
    distanceKm: 8.9,
    elevationGainFt: 1200,
    maxAltitudeFt: 960,
    typicalHours: 4,
    packWeightLb: 5,
    terrainGrade: "moderate",
    notes:
      "Rocky bald summit with NYC skyline views on clear days. Chikahoki Falls variant adds a swimming hole detour.",
    sources: ["NY-NJ Trail Conf"],
    startLat: 41.0794,
    startLng: -74.3611,
  },
  {
    slug: "pyramid-mountain",
    name: "Pyramid Mountain + Tripod Rock",
    region: "Morris County · NJ",
    country: "US",
    distanceKm: 5.0,
    elevationGainFt: 500,
    maxAltitudeFt: 934,
    typicalHours: 2.5,
    packWeightLb: 4,
    terrainGrade: "easy",
    notes:
      "Family-friendly loop past a glacial erratic (Tripod Rock — a boulder balanced on three smaller stones). Good winter hike.",
    sources: ["Morris County Parks"],
    startLat: 40.9750,
    startLng: -74.4197,
  },

  // ────── Connecticut ──────
  {
    slug: "sleeping-giant-tower-trail",
    name: "Sleeping Giant (Tower Trail)",
    region: "Sleeping Giant SP · CT",
    country: "US",
    distanceKm: 5.0,
    elevationGainFt: 750,
    maxAltitudeFt: 739,
    typicalHours: 2.5,
    packWeightLb: 4,
    terrainGrade: "easy",
    notes:
      "Old CCC-built stone tower at the summit of a traprock ridge that resembles a sleeping figure. Well-maintained approach; harder blue-blazed alternates available.",
    sources: ["CT DEEP"],
    startLat: 41.4200,
    startLng: -72.8961,
  },
  {
    slug: "bear-mountain-ct",
    name: "Bear Mountain (CT high point)",
    region: "Litchfield Hills · CT",
    country: "US",
    distanceKm: 10.5,
    elevationGainFt: 1650,
    maxAltitudeFt: 2316,
    typicalHours: 5,
    packWeightLb: 6,
    terrainGrade: "moderate",
    notes:
      "Highest peak entirely within CT (Mt Frissell has the state's high point but the summit is in MA). Stone-cairn summit, AT approach from Rt 41.",
    sources: ["CT DEEP", "AMC"],
    startLat: 42.0281,
    startLng: -73.4381,
  },

  // ────── Adirondacks (weekend-trip range) ──────
  {
    slug: "algonquin-peak",
    name: "Algonquin Peak",
    region: "Adirondacks · NY",
    country: "US",
    distanceKm: 12.9,
    elevationGainFt: 2900,
    maxAltitudeFt: 5115,
    typicalHours: 7,
    packWeightLb: 8,
    terrainGrade: "moderate",
    notes:
      "Second-highest ADK peak. Steep sustained climb from Adirondak Loj with a broad alpine summit. Weather exposure real above treeline.",
    sources: ["DEC", "ADK Guidebook"],
    startLat: 44.1830,
    startLng: -73.9647,
  },
  {
    slug: "giant-mountain",
    name: "Giant Mountain (via Roaring Brook)",
    region: "Adirondacks · NY",
    country: "US",
    distanceKm: 10.0,
    elevationGainFt: 3050,
    maxAltitudeFt: 4627,
    typicalHours: 6,
    packWeightLb: 7,
    terrainGrade: "moderate",
    notes:
      "Steep 46er with panoramic Great Range views. Roaring Brook Falls at the trailhead. Alternate approach from Chapel Pond is slightly gentler.",
    sources: ["DEC", "ADK 46er Club"],
    startLat: 44.1489,
    startLng: -73.7625,
  },
  {
    slug: "ampersand-mountain",
    name: "Ampersand Mountain",
    region: "Adirondacks · NY",
    country: "US",
    distanceKm: 8.9,
    elevationGainFt: 1780,
    maxAltitudeFt: 3352,
    typicalHours: 4.5,
    packWeightLb: 6,
    terrainGrade: "moderate",
    notes:
      "Under 3,500 ft so not an official 46er, but the bald granite summit gives one of the best 360° views in the ADK. Trail steepens dramatically in the last 0.7 mi.",
    sources: ["DEC"],
    startLat: 44.2411,
    startLng: -74.2694,
  },
  {
    slug: "mount-jo-adk",
    name: "Mount Jo",
    region: "Adirondacks · NY",
    country: "US",
    distanceKm: 4.0,
    elevationGainFt: 700,
    maxAltitudeFt: 2876,
    typicalHours: 2,
    packWeightLb: 4,
    terrainGrade: "easy",
    notes:
      "Short warm-up hike from Adirondak Loj with a bald summit and postcard view of the MacIntyre Range across Heart Lake. Ideal High Peaks primer.",
    sources: ["DEC", "ADK"],
    startLat: 44.1811,
    startLng: -73.9647,
  },
];

/**
 * Trail library augmented with coords + extra presets. Prefer this
 * over the raw TRAIL_LIBRARY for anything that cares about matching
 * or completeness.
 */
export function getFullTrailLibrary(): TrailPreset[] {
  const withCoords = TRAIL_LIBRARY.map((t) => {
    if (t.startLat != null && t.startLng != null) return t;
    const overlay = TRAIL_COORDS[t.slug];
    return overlay ? { ...t, startLat: overlay.lat, startLng: overlay.lng } : t;
  });
  // Apply Tier A detail overlay (best months, permits, water, cell,
  // parking, steepest grade, route shape) — see trail-details.ts.
  return [...withCoords, ...EXTRA_TRAIL_PRESETS].map(withDetails);
}
